import { File, FolderOpen, Image, Paperclip, Pencil, Send, Smile, Wifi } from 'lucide-react';
import { useRef, useState } from 'react';
import type { TransferItem } from '../types';

type Props = { nickname: string; onNicknameChange: (name: string) => void; relayLimit: number };
const formatSize = (size: number) => size < 1024 * 1024 ? `${Math.max(1, Math.round(size / 1024))} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`;
export function TransferWorkspace({ nickname, onNicknameChange, relayLimit }: Props) {
  const [files, setFiles] = useState<TransferItem[]>([]); const [message, setMessage] = useState(''); const [notice, setNotice] = useState(''); const input = useRef<HTMLInputElement>(null);
  const addFiles = (items: FileList | null) => { if (!items) return; const accepted: TransferItem[] = Array.from(items).filter((file) => { if (file.size > relayLimit) { setNotice(`中转文件不可超过 ${formatSize(relayLimit)}`); return false; } return true; }).map((file) => ({ id: crypto.randomUUID(), name: file.name, size: file.size, type: file.type.startsWith('image/') ? 'image' : 'file', sentAt: new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) })); setFiles((current) => [...current, ...accepted]); };
  return <main className="workspace"><section className="peer-panel"><div className="peer-avatar">柚</div><div><div className="peer-title">与 {nickname} 传输中 <button className="icon-button" onClick={() => { const next = window.prompt('设置你的昵称', nickname); if (next) onNicknameChange(next); }}><Pencil size={14} /></button></div><span className="connection"><Wifi size={13} /> 已连接 · 局域网优先</span></div></section><section className="message-area"><div className="date-separator">今天</div>{files.length === 0 && <div className="empty-transfer"><Image size={36} /><strong>已建立安全连接</strong><span>拖入文件、图片或发送消息</span></div>}{files.map((file) => <article className="file-message" key={file.id}><span className={file.type === 'image' ? 'file-type image' : 'file-type'}>{file.type === 'image' ? <Image size={21} /> : <File size={21} />}</span><span><strong>{file.name}</strong><small>{formatSize(file.size)}</small></span><time>{file.sentAt}</time></article>)}{message && <article className="text-message">{message}</article>}</section><section className="composer">{notice && <span className="notice">{notice}</span>}<input ref={input} hidden type="file" multiple onChange={(event) => addFiles(event.target.files)} /><button className="icon-button" onClick={() => input.current?.click()} aria-label="选择文件"><Paperclip size={20} /></button><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && message.trim()) setMessage(''); }} placeholder="输入消息或拖拽文件到此处" /><button className="icon-button" aria-label="表情"><Smile size={20} /></button><button className="icon-button" onClick={() => input.current?.click()} aria-label="文件夹"><FolderOpen size={20} /></button><button className="send-button" onClick={() => setMessage('')} aria-label="发送"><Send size={18} /></button></section></main>;
}
