export type Pairing = { code: string; expiresAt: string };
export type Presence = { deviceId: string; online: boolean; nickname?: string; avatar?: string };
export type IceServerConfig = { urls: string[]; username?: string; credential?: string };
export type RtcConfig = { relayMaxFileSize: number; iceServers: IceServerConfig[] };
export type DeviceProfile = { nickname: string; avatar: string };
export type TransferStatus = typeof TRANSFER_STATUS[keyof typeof TRANSFER_STATUS];
export type TransferItem = { id: string; name: string; size: number; type: 'file' | 'image'; sentAt: string; direction: 'incoming' | 'outgoing'; text?: string; objectUrl?: string; progress?: number; transferredBytes?: number; speedBytes?: number; remainingSeconds?: number; elapsedSeconds?: number; expired?: boolean; transferStatus?: TransferStatus };
export type View = 'connect' | 'conversations' | 'transfer' | 'tutorial' | 'settings' | 'about';
export type Conversation = { deviceId: string; nickname: string; remark?: string; avatar: string; online: boolean; blocked: boolean; messages: TransferItem[]; lastConnectedAt: string };
import type { TRANSFER_STATUS } from './constants';
